# Generated by Django 5.1 on 2024-10-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
