# Generated by Django 5.1 on 2024-10-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_cartmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
