# Generated by Django 5.1 on 2024-10-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
