# Generated by Django 5.1 on 2024-11-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_likemodel_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='count',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
