# Generated by Django 5.1 on 2024-11-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_ordermodel_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product_id',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pages.productmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_ru',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description_uz',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_ru',
            field=models.CharField(default='1', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='title_uz',
            field=models.CharField(default='1', max_length=155),
            preserve_default=False,
        ),
    ]
