# Generated by Django 5.1 on 2024-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_rename_description_productmodel_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchesmodel',
            old_name='address',
            new_name='address_en',
        ),
        migrations.RenameField(
            model_name='branchesmodel',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='branchesmodel',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branchesmodel',
            name='address_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branchesmodel',
            name='name_ru',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchesmodel',
            name='name_uz',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
