# Generated by Django 5.1 on 2024-11-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_branchesmodel_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchesmodel',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branchesmodel',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
