# Generated by Django 5.1 on 2024-11-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
