# Generated by Django 5.1 on 2024-11-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_cartmodel_likemodel_ordermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartModel',
        ),
        migrations.DeleteModel(
            name='LikeModel',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
