# Generated by Django 5.1 on 2024-11-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_cartmodel_likemodel_ordermodel_delete_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchesmodel',
            name='region',
            field=models.CharField(choices=[('TASHKENT', 'TASHKENT'), ('SAMARKAND', 'SAMARKAND')], default='TASHKENT', max_length=100),
        ),
    ]
